import java.text.SimpleDateFormat

node {
    def rose_deps

    def dateFormat = new SimpleDateFormat("yyyy-MM-dd")
    def todaysDate = new Date()

    println()

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        dir('rose-dependencies') {
            rose_deps = docker.build("rosecompiler/rose-dependencies", "--no-cache")
        }
    }

    stage('Test image') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */
        sh 'echo "Tests passed"'
    }

    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            //rose_deps.push("centos7-${env.BUILD_NUMBER}")
            rose_deps.push("centos7-" + dateFormat.format(todaysDate))
            rose_deps.push("centos7-latest")
        }
    }
}
