import java.text.SimpleDateFormat

node {
    def rose_edg

    def dateFormat = new SimpleDateFormat("yyyy-MM-dd")
    def todaysDate = new Date()
    def roseVersion = sh ( script: 'curl https://raw.githubusercontent.com/rose-compiler/rose-develop/master/ROSE_VERSION', returnStdout: true).trim()

    println()

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        dir('rose-edg') {
            // Runs as root in Jenkins docker container
            sh 'rm -rf ubuntu-16.04/EDG/'
            sh 'GIT_SSH_COMMAND="ssh -i /var/jenkins_home/bitbucket/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone --depth 1 git@bitbucket.org:rose-compiler/edg.git ubuntu-16.04/EDG'

            rose_edg = docker.build("rosecompiler/rose-edg", "--no-cache ubuntu-16.04")
            sh 'rm -rf ubuntu-16.04/EDG/'
        }
    }

    stage('Test image') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */
        sh 'echo "Tests passed"'
    }

    stage('Upload EDG Binary') {
        customImage.inside('-v $WORKSPACE:/output -u root') {
            sh """
            ls /root/Downloads
            cp /root/Downloads/* /output
            """ 
        }
        archiveArtifacts artifacts: '*.tar.gz'
    }

    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            //rose_edg.push("ubuntu-16.04-${env.BUILD_NUMBER}")
            //rose_edg.push("ubuntu-16.04-" + dateFormat.format(todaysDate))
            rose_edg.push("ubuntu-16.04-${roseVersion}")
        }
    }
}
