node {
    println()

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Disk Usage Before') {
    	sh('df -h .')
    }

    stage('Remove Exited Containers') {
    	sh('(test -n "$(docker ps -a -f status=exited -q)" && docker rm $(docker ps -a -f status=exited -q)) || true')
    }

    stage('Remove Dangling Images') {
    	sh('(test -n "$(docker images -q -f dangling=true)" && docker rmi $(docker images -q -f dangling=true)) || true')
    }

    stage('Prune All') {
    	sh('docker system prune --all --force')
    }

    stage('Disk Usage After') {
    	sh('df -h .')
    }
}
